name: GitHub Actions Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '15 20 * * *'

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@gitlab.com:${{ github.repository }}.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}

  mirror_to_bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: 'Mirror to bitbucket'
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@bitbucket.org:${{ github.repository }}.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}